# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0


In [18]:
#1
import numpy as np

arr = np.random.uniform(0, 20, 28)
arr = arr.reshape(4, 7)

min_val = np.min(arr)
max_val = np.max(arr)

a = 1.0 / (max_val - min_val)
b = max_val-min_val
normalized_arr = a*arr + b

print("Исходный массив:")
print(arr)
print("Нормализованный массив:")
print(normalized_arr)


Исходный массив:
[[18.49836331 19.65970015 13.98136105 16.29499213  9.21833379  7.47712782
   5.74691542]
 [ 5.23551796 17.27667914 15.62137003  2.92711543  6.64680448  4.78251062
   5.27367096]
 [ 4.70599734  9.7761112   9.20416207  3.30840225 17.09470087 14.47568611
   6.17940563]
 [ 0.74309773 14.73549538  1.3919034   5.87534391 19.96886237 12.58394914
  15.08919339]]
Нормализованный массив:
[[20.18792992 20.24833516 19.95298466 20.07332479 19.70524277 19.61467649
  19.52468203]
 [19.49808244 20.12438581 20.03828733 19.37801426 19.57148844 19.47451992
  19.50006691]
 [19.4705402  19.73425475 19.70450565 19.39784633 20.11492047 19.97869625
  19.54717737]
 [19.26441578 19.99220985 19.29816245 19.53136205 20.26441578 19.88030033
  20.01060694]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [19]:
import numpy as np

arr = np.random.randint(0, 11, (8, 10))
print(arr)

sums = np.sum(arr, axis=1)
minimum = np.argmin(sums)
print('\n', arr[minimum])
print(minimum)

[[ 5  5  4  1  0  6  4  7  2  3]
 [ 4  1  4  0  9  2  4  0  0  1]
 [ 4  9  1  2 10  4  3  9  3 10]
 [ 1  9  7  5  9  2  9 10  7  1]
 [ 7  2  1  3  8  7 10  6  7  4]
 [ 6  6  9  2  9  1  9 10  2  8]
 [10  8  3  8  9  0 10  1  1  8]
 [ 1  8  3  8  0  4  8  3  7  9]]

 [4 1 4 0 9 2 4 0 0 1]
1



3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [20]:
import numpy as np

v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

e_distance = np.linalg.norm(v1 - v2)

print("Евклидово расстояние между вектором 1 и вектором 2:", e_distance)

Евклидово расстояние между вектором 1 и вектором 2: 5.196152422706632


4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [21]:
import numpy as np

A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])

X = np.linalg.inv(A) @ (-C) @ (np.linalg.inv(B))

print(X)

[[ 1.00000000e+00  5.32907052e-16]
 [-2.00000000e+00  1.00000000e+00]
 [ 3.00000000e+00 -4.00000000e+00]]


## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [22]:
import numpy as np 

In [23]:
data = np.loadtxt('D:\\code\\TOD_ID23-2\\data\\minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
#1
print('#1', data[:5])

#1 [[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


In [24]:
data

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [25]:
#2
min_val_2 = np.min(data[:, 1])
max_val_2 = np.max(data[:, 1])
min_val_3 = np.min(data[:, 2])
max_val_3 = np.max(data[:, 2])
print('#2', min_val_2, max_val_2, min_val_3, max_val_3)
mn_2 = np.mean(data[:, 1])
mn_3 = np.mean(data[:, 2])
med_2 = np.median(data[:, 1])
med_3 = np.median(data[:, 2])

#2 0 2147483647 1 39


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [26]:
#3
print('\n#3', np.quantile(data[:, 1], 0.75))


#3 65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [27]:
#4
data = np.where(data == 0, 1, data)

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [28]:
#5
len(np.unique(data[:, 0]))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [29]:
#6 
print('\n#6\n', np.unique(data[:, 2]), '\n',  len(np.unique(data[:, 2])))


#6
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39] 
 37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [32]:
data[data[:, 2] < 6]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [162]:
for i in data[:, 2] / data[:, 1]:
    print(i)


0.26666666666666666
0.28
0.6
1.2
0.23333333333333334
0.175
0.5
0.3333333333333333
1.2857142857142858
0.35
0.3076923076923077
0.5833333333333334
0.12941176470588237
0.6
0.2
0.6666666666666666
0.5833333333333334
0.03888888888888889
0.1625
0.3
0.8
0.15714285714285714
0.01904761904761905
0.07333333333333333
0.11666666666666667
0.21176470588235294
0.15
0.2222222222222222
0.1
0.016
0.55
0.05384615384615385
0.1
0.09166666666666666
0.23333333333333334
0.07333333333333333
0.01981981981981982
0.25
0.15555555555555556
0.4
0.8
0.16
0.32
0.14545454545454545
2.0
0.07272727272727272
0.4
1.0
0.24
0.4
0.45714285714285713
0.5625
0.5333333333333333
0.3
0.2
0.008291873963515755
0.020202020202020204
0.075
0.4
0.07692307692307693
0.15
1.0
0.04285714285714286
0.014141414141414142
0.7
0.15714285714285714
0.2
0.06896551724137931
0.46153846153846156
0.1
0.4
0.4
0.3
0.12
0.1625
0.28
0.06153846153846154
0.06666666666666667
0.3076923076923077
0.16666666666666666
0.07692307692307693
0.3333333333333333
0.04615384615

In [163]:
(data[:, 2] / data[:, 1]).max()

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [164]:
sorted_data = data[data[:, 1]. argsort ()[:: -1]][:100]
sorted_data

array([[    261647, 2147483647,          8],
       [    216215,     259260,          7],
       [    425681,     259205,          2],
       [     98912,     216015,          4],
       [     70551,     201610,          7],
       [    236340,     146880,          5],
       [    242032,     132495,          3],
       [    184528,     129620,          3],
       [    236274,     129615,          5],
       [    236281,     129615,          5],
       [     13264,     115230,          4],
       [    105417,      86405,          2],
       [     41403,      86400,          4],
       [     34175,      86400,          3],
       [    142936,      86400,          9],
       [     93063,      86400,          2],
       [     42247,      69120,          2],
       [    255611,      64815,          3],
       [    140344,      60555,          3],
       [    101082,      60540,          7],
       [     46288,      50405,          5],
       [    246196,      44655,          4],
       [  

In [165]:
sorted_data[:, 2].mean()

6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [166]:
#10
for i in range(10):
    print(*data[data[:, 0] == np.random.choice(data[:, 0])])

[197132     16      6]
[258750    375      6]
[52097    25     5]
[342917     20      8]
[80073    80     6]
[34405    27    10]
[341769      2      4]
[473713    250     14]
[180394     25      7]
[172752    170     16]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [167]:
mean_ing = data[:, 2].mean()
data[data[:, 2] < mean_ing]

array([[ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       ...,
       [371794,     35,      8],
       [ 43407,     35,      7],
       [370915,      5,      4]])

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [168]:
data[((data[:, 1] < 20) & (data[:, 2] < 6))]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 60756,     15,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

In [169]:
data[((data[:, 1] < 20) & (data[:, 2] < 6))].shape

(8315, 3)

In [170]:
data.shape

(100000, 3)

13. Выведите процент "простых" рецептов в датасете

In [171]:
8315 / 100000 * 100

8.315

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [172]:
short = data[data[:, 1] < 10]
medium = data[(data[:, 1] > 10) & (data[:, 1] < 20)]
long = data[data[:, 1] > 19]
minimum = np.array([short.shape[0], medium.shape[0], long.shape[0]]).min()

res_array = np.array([short[:minimum], medium[:minimum], long[:minimum]])
res_array.shape

(3, 7588, 3)

In [173]:
res_array[0] #ndarray 'short' по 0 оси 

array([[ 67660,      5,      6],
       [366174,      7,      9],
       [204134,      5,      3],
       ...,
       [420725,      5,      3],
       [  4747,      1,      9],
       [370915,      5,      4]])

In [174]:
res_array[1] #ndarray 'medium'по 0 оси

array([[ 33941,     18,      9],
       [446597,     15,      5],
       [ 81006,     12,      7],
       ...,
       [278297,     12,      7],
       [ 66970,     15,      8],
       [ 90921,     18,      8]])

In [175]:
data.shape

(100000, 3)